import bebederoImg from '../assets/img/products/aves/bebedero.png';


const productsData = [
    {
        id: 1,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "aves",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: bebederoImg,
        reviews: 120,
        novedad: "si",
    },
    {
        id: 2,
        nombre: "aves",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: bebederoImg,
        reviews: 90,
        novedad: "si",
    },

    {
        id: 3,
        nombre: "aves",
        puntuacion: 4.5,
        categoria: "aves",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: bebederoImg,
        reviews: 120,
        novedad: "si",
    },
    {
        id: 4,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "si",
    },
    {
        id: 5,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
        novedad: "no",
    },
    {
        id: 6,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "no",
    },
    {
        id: 7,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "no",
    },

    {
        id: 8,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        descripcion:"descripcion",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
        novedad: "no",
    },
    {
        id: 9,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"descripcion",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "no",
    },
    {
        id: 10,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        descripcion:"descripcion",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
        novedad: "no",
    },
    {
        id: 11,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"descripcion",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "no",
    },
    {
        id: 12,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"descripcion",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "no",
    },
    {
        id: 13,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "no",
    },
    {
        id: 14,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        descripcion:"hola como estas esto es una descripcion corta que le estoy insertando para probar",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
        novedad: "no",
    },

];

export default productsData;
