const productsData = [
    {
        id: 1,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
    },
    {
        id: 2,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },

    {
        id: 3,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
    },
    {
        id: 4,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },
    {
        id: 5,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
    },
    {
        id: 6,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },
    {
        id: 7,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },

    {
        id: 8,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
    },
    {
        id: 9,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },
    {
        id: 10,
        nombre: "Producto 1",
        puntuacion: 4.5,
        categoria: "Categoría 1",
        imagen: "url_imagen_1.jpg",
        reviews: 120,
    },
    {
        id: 11,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },
    {
        id: 12,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },
    {
        id: 13,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },
    {
        id: 14,
        nombre: "Producto 2",
        puntuacion: 3.8,
        categoria: "Categoría 2",
        imagen: "url_imagen_2.jpg",
        reviews: 90,
    },

];

export default productsData;
